/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      "colors": {
        "outline-variant": "#3f4941",
        "error-container": "#93000a",
        "surface-bright": "#37393e",
        "secondary-fixed-dim": "#f4be45",
        "on-background": "#e2e2e8",
        "on-primary-fixed-variant": "#00522d",
        "surface-container-low": "#1a1c20",
        "surface-variant": "#333539",
        "primary": "#88d7a2",
        "on-secondary-fixed": "#261900",
        "secondary-container": "#b88909",
        "on-secondary-container": "#382700",
        "outline": "#89938a",
        "background": "#111317",
        "tertiary": "#ffb688",
        "on-surface": "#e2e2e8",
        "on-secondary-fixed-variant": "#5c4300",
        "inverse-primary": "#186c40",
        "on-surface-variant": "#bfc9bf",
        "on-tertiary-fixed-variant": "#733500",
        "on-error-container": "#ffdad6",
        "tertiary-fixed-dim": "#ffb688",
        "surface-dim": "#111317",
        "surface-container": "#1e2024",
        "on-primary": "#00391e",
        "on-primary-container": "#003119",
        "on-primary-fixed": "#00210f",
        "on-error": "#690005",
        "primary-fixed-dim": "#88d7a2",
        "surface": "#111317",
        "surface-container-lowest": "#0c0e12",
        "inverse-surface": "#e2e2e8",
        "inverse-on-surface": "#2f3035",
        "tertiary-container": "#d9772e",
        "error": "#ffb4ab",
        "primary-container": "#52a070",
        "on-tertiary": "#512400",
        "surface-tint": "#88d7a2",
        "secondary-fixed": "#ffdea1",
        "secondary": "#f4be45",
        "tertiary-fixed": "#ffdbc7",
        "primary-fixed": "#a3f4bd",
        "on-secondary": "#402d00",
        "surface-container-high": "#282a2e",
        "on-tertiary-fixed": "#311300",
        "on-tertiary-container": "#471e00",
        "surface-container-highest": "#333539"
      },
      "borderRadius": {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.5rem",
        "full": "0.75rem"
      },
      "spacing": {
        "space-2xl": "48px",
        "space-xs": "4px",
        "space-md": "16px",
        "panel-padding": "28px",
        "grid-gutter": "24px",
        "space-lg": "24px",
        "space-sm": "8px",
        "space-xl": "32px",
        "space-3xl": "64px"
      },
      "fontFamily": {
        "body-sm": ["IBM Plex Sans"],
        "telemetry-num": ["IBM Plex Sans"],
        "display-hero-mobile": ["IBM Plex Sans"],
        "label-caps": ["IBM Plex Sans"],
        "telemetry-unit": ["IBM Plex Sans"],
        "body-lg": ["IBM Plex Sans"],
        "headline-sm": ["IBM Plex Sans"],
        "headline-lg": ["IBM Plex Sans"],
        "display-hero": ["IBM Plex Sans"]
      }
    },
  },
  plugins: [],
}
